# Generated by Django 5.1.2 on 2024-11-03 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('location', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Lounge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('terminal', models.CharField(blank=True, max_length=100, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lounges', to='locations.airport')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('lounge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='locations.lounge')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lounge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='locations.lounge')),
            ],
        ),
        migrations.CreateModel(
            name='EntryCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_stay_duration', models.DurationField()),
                ('lounge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_conditions', to='locations.lounge')),
            ],
        ),
        migrations.CreateModel(
            name='LoungeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from_time', models.TimeField()),
                ('valid_till_time', models.TimeField()),
                ('valid_days', models.JSONField()),
                ('lounge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='locations.lounge')),
            ],
        ),
    ]
